name: GitHub Pages Deploy

on:
  push:
    branches:
      - main # 或 master，取决于你的默认分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # 升级到 v3，更稳定

      - name: Set up Node.js
        uses: actions/setup-node@v3 # 升级到 v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci # 使用 npm ci，更快更可靠

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # 推荐使用 peaceiris/actions-gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 使用 GITHUB_TOKEN，这是关键！
          publish_dir: ./dist/iot-statistics/browser # 你的构建输出目录
          # cname: yourdomain.com # 如果你使用自定义域名，请取消注释并填写你的域名
          # force_orphan: true # 仅在首次部署到 gh-pages 分支时需要